import React from 'react'
import AboutUsComp from './AboutUsComp'
import Title from '../components/Title'
import AboutBg from '../components/AboutBg'
import AboutWho from '../components/AboutWho'

export const metadata = {
    title: "About Us",
    description: "Generated by create next app",
};

export default function AboutUs() {
    return (
        <div>
            <Title />
            <AboutUsComp />
            <AboutWho />
            <AboutBg />
        </div>
    )
}
