import React from 'react'
import Title from '../components/Title'
import PortfolioComp from './PortfolioComp'

export const metadata = {
    title: "Portfolio",
    description: "Generated by create next app",
};

export default function Portfolio() {
    return (
        <div>
            <Title />
            <PortfolioComp />
        </div>
    )
};