import AboutBg from "./components/AboutBg";
import Brands from "./components/brands/brands";
import CarouselComp from "./components/carousel/CarouselComp";
import Funfact from "./components/funfact/funfact";
import Header from "./components/header/header";
import Section from "./components/section/section";
import Team from "./team/team";
import ServicesComp from "./services/Services";
import Modal from "./components/modal/Modal";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <Header />
      <Funfact />
      <ServicesComp />
      <CarouselComp />
      <Section />
      <Brands />
      <Team />
      <AboutBg />
      <Modal />
    </div>
  );
};